base_url = "/"
title = "千虑者"
description = "(✿╹◡╹) 智者千虑必有一失,愚者千虑必有一得(╹◡╹✿)"
default_language = "zh"

# 添加分类支持
taxonomies = [
    {name = "tags", feed = true}, # 标签分类
]

[markdown]
# 启用自定义 HTML
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "千虑者"
# 添加自定义配置
enable_line_numbers = true 

[[extra.search]]
name = "search"
template = "search-results.html"
path = "search" 