base_url = "/"
title = "千虑者"
description = "(✿╹◡╹) 智者千虑必有一失,愚者千虑必有一得(╹◡╹✿)"
default_language = "zh"

# 启用搜索索引构建
build_search_index = true

# 标签分类配置
taxonomies = [
    {name = "tags", feed = true, rss = true}
]

[markdown]
# 启用语法高亮
highlight_code = true
highlight_theme = "css"  # 使用CSS类而非内联样式，支持主题切换

# 生成语法高亮CSS文件，支持暗色/亮色主题
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]

# 启用表格支持
render_emoji = true
# 启用脚注
external_links_target_blank = true
# 启用智能标点
smart_punctuation = true

[extra]
author = "千虑者"
subtitle = "个人博客"
keywords = "博客,技术,编程,生活,Rust,Zola"
description = "(✿╹◡╹) 智者千虑必有一失,愚者千虑必有一得(╹◡╹✿)"

# SEO 相关配置
[extra.seo]
google_site_verification = ""  # Google Search Console 验证码
baidu_site_verification = ""   # 百度站长验证码
bing_site_verification = ""    # Bing Webmaster 验证码

# 站点地图配置
generate_sitemap = true
sitemap_filename = "sitemap.xml"

# 添加自定义配置
enable_line_numbers = true

# 搜索配置
[search]
index_format = "fuse_json"              # 中文推荐使用Fuse.js
include_title = true
include_content = true  
include_description = true
truncate_content_length = 1500          # 适合中文博客长度

[extra.theme]
auto_dark = true  # 启用自动夜间模式
dark_mode_time = { start = 19, end = 7 }  # 夜间模式时间范围，19:00-07:00 