base_url = "/"
title = "千虑者"
description = "(✿╹◡╹) 智者千虑必有一失,愚者千虑必有一得(╹◡╹✿)"
default_language = "zh"

# 标签分类配置
taxonomies = [
    {name = "tags", feed = true, rss = true}
]

[markdown]
# 启用语法高亮
highlight_code = true
# 启用表格支持
render_emoji = true
# 启用脚注
external_links_target_blank = true
# 启用智能标点
smart_punctuation = true

[extra]
author = "千虑者"
subtitle = "个人博客"
keywords = "博客,技术,编程,生活,Rust,Zola"
description = "(✿╹◡╹) 智者千虑必有一失,愚者千虑必有一得(╹◡╹✿)"

# SEO 相关配置
[extra.seo]
google_site_verification = ""  # Google Search Console 验证码
baidu_site_verification = ""   # 百度站长验证码
bing_site_verification = ""    # Bing Webmaster 验证码

# 站点地图配置
generate_sitemap = true
sitemap_filename = "sitemap.xml"

# 添加自定义配置
enable_line_numbers = true 

[extra.search]
name = "search"
template = "search-results.html"
path = "search"
# 搜索API端点配置
api_endpoint = "/search"
# 每页结果数
results_per_page = 10
# 搜索结果页面路径
search_path = "search" 